version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  builder: html
  configuration: docs/conf.py

python:
  install:
    - method: pip
    - requirements: Read_the_Docs/requirements.txt
