services:
  workspace-kndc:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - BUILD_ENV

    environment:
      - KNDC_API_KEY_FMP
      - KNDC_API_KEY_LSEG
      - KNDC_API_KEY_INTRINIO
      - KNDC_DEBUG_PORT
